# Generated by Django 2.2.3 on 2019-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
