# Generated by Django 2.2.3 on 2019-07-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190709_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrecord',
            old_name='id',
            new_name='idnum',
        ),
    ]
