# Generated by Django 2.2.3 on 2019-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190709_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrecord',
            name='idnum',
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
